//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Resources.Settings.Currencies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CurrencyRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigoErp.Resources.Settings.Currencies.CurrencyRes", typeof(CurrencyRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Amount.
        /// </summary>
        public static string AfterAmount {
            get {
                return ResourceManager.GetString("AfterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Amount.
        /// </summary>
        public static string BeforeAmount {
            get {
                return ResourceManager.GetString("BeforeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage currencies and set their rates.
        /// </summary>
        public static string CreateAndManage {
            get {
                return ResourceManager.GetString("CreateAndManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Mark.
        /// </summary>
        public static string DecimalMark {
            get {
                return ResourceManager.GetString("DecimalMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Currency.
        /// </summary>
        public static string EditCurrency {
            get {
                return ResourceManager.GetString("EditCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Decimal Mark.
        /// </summary>
        public static string EnterDecimalMark {
            get {
                return ResourceManager.GetString("EnterDecimalMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Precision.
        /// </summary>
        public static string EnterPrecision {
            get {
                return ResourceManager.GetString("EnterPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Rate.
        /// </summary>
        public static string EnterRate {
            get {
                return ResourceManager.GetString("EnterRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Symbol.
        /// </summary>
        public static string EnterSymbol {
            get {
                return ResourceManager.GetString("EnterSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Thousands Separator.
        /// </summary>
        public static string EnterThousandsSeparator {
            get {
                return ResourceManager.GetString("EnterThousandsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Currency.
        /// </summary>
        public static string NewCurrency {
            get {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Code -.
        /// </summary>
        public static string SelectCode {
            get {
                return ResourceManager.GetString("SelectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Symbol Position -.
        /// </summary>
        public static string SelectSymbolPosition {
            get {
                return ResourceManager.GetString("SelectSymbolPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Position.
        /// </summary>
        public static string SymbolPosition {
            get {
                return ResourceManager.GetString("SymbolPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands Separator.
        /// </summary>
        public static string ThousandsSeparator {
            get {
                return ResourceManager.GetString("ThousandsSeparator", resourceCulture);
            }
        }
    }
}
