//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Resources.Purchase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigoErp.Resources.Purchase.PaymentRes", typeof(PaymentRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payment.
        /// </summary>
        public static string EditPayment {
            get {
                return ResourceManager.GetString("EditPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount.
        /// </summary>
        public static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Refrence.
        /// </summary>
        public static string EnterRefrence {
            get {
                return ResourceManager.GetString("EnterRefrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Payment.
        /// </summary>
        public static string NewPayment {
            get {
                return ResourceManager.GetString("NewPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence.
        /// </summary>
        public static string Refrence {
            get {
                return ResourceManager.GetString("Refrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account.
        /// </summary>
        public static string SelectAccount {
            get {
                return ResourceManager.GetString("SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bill.
        /// </summary>
        public static string SelectBill {
            get {
                return ResourceManager.GetString("SelectBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture.
        /// </summary>
        public static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vendor.
        /// </summary>
        public static string SelectVendor {
            get {
                return ResourceManager.GetString("SelectVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
    }
}
