//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigoErp_Db : DbContext
    {
        public DigoErp_Db()
            : base("name=DigoErp_Db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Branch> Tbl_Branch { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_ItemUnit> Tbl_ItemUnit { get; set; }
        public virtual DbSet<Tbl_Item> Tbl_Item { get; set; }
        public virtual DbSet<Tbl_Vendor> Tbl_Vendor { get; set; }
        public virtual DbSet<Tbl_Currency> Tbl_Currency { get; set; }
        public virtual DbSet<Tbl_Tax> Tbl_Tax { get; set; }
        public virtual DbSet<Tbl_Account> Tbl_Account { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_InvoiceItem> Tbl_InvoiceItem { get; set; }
        public virtual DbSet<Tbl_Default> Tbl_Default { get; set; }
        public virtual DbSet<Tbl_Bill_Item> Tbl_Bill_Item { get; set; }
        public virtual DbSet<Tbl_Customer> Tbl_Customer { get; set; }
        public virtual DbSet<Tbl_Transaction> Tbl_Transaction { get; set; }
        public virtual DbSet<Tbl_Invoice> Tbl_Invoice { get; set; }
        public virtual DbSet<Tbl_Bill> Tbl_Bill { get; set; }
        public virtual DbSet<Tbl_Transfer> Tbl_Transfer { get; set; }
        public virtual DbSet<Tbl_Reconciliation> Tbl_Reconciliation { get; set; }
        public virtual DbSet<Tbl_Reconciliation_Transaction> Tbl_Reconciliation_Transaction { get; set; }
    }
}
