//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Bill()
        {
            this.Tbl_Bill_Items = new HashSet<Tbl_Bill_Item>();
            this.Tbl_Transaction = new HashSet<Tbl_Transaction>();
        }
    
        public long Id { get; set; }
        public Nullable<long> VendorId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public string BillDate { get; set; }
        public string DueDate { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<int> Recurring { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Discount_Percentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Bill_Item> Tbl_Bill_Items { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Currency Tbl_Currency { get; set; }
        public virtual Tbl_Vendor Tbl_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaction> Tbl_Transaction { get; set; }
    }
}
