//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Default = new HashSet<Tbl_Default>();
            this.Tbl_Reconciliation = new HashSet<Tbl_Reconciliation>();
        }
    
        public long Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Photo { get; set; }
        public string Password { get; set; }
        public string ResetPasswordCode { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public string LandingPage { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Tbl_Branch Tbl_Branch { get; set; }
        public virtual Tbl_Role Tbl_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Default> Tbl_Default { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reconciliation> Tbl_Reconciliation { get; set; }
    }
}
