//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transfer
    {
        public long Id { get; set; }
        public Nullable<long> FromAccount { get; set; }
        public Nullable<long> ToAccount { get; set; }
        public string Amount { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        public virtual Tbl_Account Tbl_AccountFrom { get; set; }
        public virtual Tbl_Account Tbl_AccountTo { get; set; }
    }
}
