//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Invoice()
        {
            this.Tbl_InvoiceItems = new HashSet<Tbl_InvoiceItem>();
        }
    
        public long Id { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public string InvoiceDate { get; set; }
        public string DueDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string OrderNumber { get; set; }
        public string Notes { get; set; }
        public string Footer { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<int> Recurring { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Discount_Percentage { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Currency Tbl_Currency { get; set; }
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InvoiceItem> Tbl_InvoiceItems { get; set; }
    }
}
