//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transaction
    {
        public long Id { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string Description { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<int> Recurring { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string Reference { get; set; }
        public string Attachment { get; set; }
        public Nullable<long> Invoice { get; set; }
        public Nullable<long> BillId { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_Vendor Tbl_Vendor { get; set; }
        public virtual Tbl_Bill Tbl_Bill { get; set; }
    }
}
