//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Item
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> TaxId { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
    
        public virtual Tbl_Tax Tbl_Tax { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
