//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Reconciliation_Transaction
    {
        public long Id { get; set; }
        public Nullable<long> ReconciliationId { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Withdrawal { get; set; }
        public Nullable<bool> IsClear { get; set; }
    
        public virtual Tbl_Reconciliation Tbl_Reconciliation { get; set; }
    }
}
