//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigoErp.Repository.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Account()
        {
            this.Tbl_Defaults = new HashSet<Tbl_Default>();
            this.Tbl_Transaction = new HashSet<Tbl_Transaction>();
            this.Tbl_TransfersFrom = new HashSet<Tbl_Transfer>();
            this.Tbl_TransfersTo = new HashSet<Tbl_Transfer>();
            this.Tbl_Reconciliation = new HashSet<Tbl_Reconciliation>();
        }
    
        public long Id { get; set; }
        public string Number { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string BankName { get; set; }
        public string BankPhone { get; set; }
        public string BankAddress { get; set; }
        public Nullable<bool> DefaultAccount { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string AccountName { get; set; }
        public string IBANNumber { get; set; }
    
        public virtual Tbl_Currency Tbl_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Default> Tbl_Defaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaction> Tbl_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transfer> Tbl_TransfersFrom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transfer> Tbl_TransfersTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reconciliation> Tbl_Reconciliation { get; set; }
    }
}
